artifacts_root: artifacts


data_ingestion_1: 
  root_dir: artifacts/data_ingestion
  source_url: none
  local_data_file:  artifacts/data_ingestion/dataset.zip
  unzip_dir: artifacts/data_ingestion
  zip_file_dir: dataset
  dataset_source: dataset/dataset.zip
  coordinates_path: artifacts/data_ingestion/dataset/train_solution_bounding_boxes (1).csv
  coordinates_target_path: artifacts/data_ingestion/dataset/train_images

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: none
  local_data_file:  artifacts/prepare_base_model/yolo/dataset.zip
  unzip_dir: artifacts/prepare_base_model/yolo
  zip_file_dir: dataset
  dataset_source: dataset/dataset.zip
  coordinates_path: artifacts/prepare_base_model/yolo/dataset/train_solution_bounding_boxes (1).csv
  coordinates_target_path: artifacts/prepare_base_model/yolo/dataset/train_images


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_link: https://github.com/ultralytics/yolov5.git
  base_model_path: artifacts/prepare_base_model/yolo

  